config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'prototypes#index'
  get '/users/sign_out', to: 'sessions#destroy'

  resources :prototypes do
    resources :comments, only: [:create, :destroy, :edit, :update]
  end

  resources :users, only: [:show]
end

app/models/age.rb
class Age < ActiveHash::Base
  self.data = [
    { id: 0, name: '10代' },
    { id: 1, name: '20代' },
    { id: 2, name: '30代' },
    { id: 3, name: '40代' },
    { id: 4, name: '壮年' },
    { id: 5, name: '老年' },
  ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :prototype

  validates :content, presence: true
end

app/models/gender.rb
class Gender < ActiveHash::Base
  self.data = [
    { id: 0, name: '男性' },
    { id: 1, name: '女性' },
    { id: 2, name: 'その他' }
  ]
end

app/models/occupation.rb
class Occupation < ActiveHash::Base
  self.data = [
    { id: 0, name: '村人' },
    { id: 1, name: 'かませ犬' },
    { id: 2, name: '商人' },
  ]
end

app/models/prototype.rb
class Prototype < ApplicationRecord
   # Active Hash の関連付けを有効にする
   extend ActiveHash::Associations::ActiveRecordExtensions

  # バリデーション
  validates :title, presence: true
  validates :catch_copy, presence: true
  validates :concept, presence: true

  belongs_to :user
  belongs_to_active_hash :gender
  belongs_to_active_hash :age
  belongs_to_active_hash :occupation

  has_many :comments, dependent: :destroy

  # ActiveStorageの設定
  has_one_attached :image

  # 画像の存在チェックバリデーション
  validate :image_presence

  private
  #画像がないと投稿できない設定
  def image_presence
    errors.add(:image, "can't be blank") unless image.attached?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :nickname, presence: true
  validates :profile, presence: true
  validates :occupation, presence: true
  validates :position, presence: true

  has_many :prototypes
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :email, :password, :password_confirmation, :profile, :occupation, :position])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def create
    @prototype = Prototype.find(params[:prototype_id])
    @comment = @prototype.comments.new(comment_params)
    if @comment.save
      redirect_to prototype_path(@prototype)
    else
      @comments = @prototype.comments
      render "prototypes/show"
    end
  end
  

  private

  def comment_params
    params.require(:comment).permit(:content, :prototype_id).merge(user_id: current_user.id)
  end
end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :destroy]
  before_action :move_to_index, except: [:index, :show]

  def index
    @prototypes = Prototype.all
    
    if params[:gender_id].present?
      @prototypes = @prototypes.where(gender_id: params[:gender_id])
    end
  
    if params[:age_id].present?
      @prototypes = @prototypes.where(age_id: params[:age_id])
    end
  end

  def new
    @prototype = Prototype.new
  end

  def create
  @prototype = Prototype.new(prototype_params)
    if @prototype.save
    redirect_to root_path
   else
    render :new
   end
  end

  def show
    @prototype = Prototype.find(params[:id])
    @comment = Comment.new
    @comments = @prototype.comments 
  end

  def edit
    @prototype = Prototype.find(params[:id])
    redirect_to root_path unless current_user.id == @prototype.user_id
  end

  def update
    @prototype = Prototype.find(params[:id])
    if @prototype.update(prototype_params)
      redirect_to prototype_path(@prototype)
    else
      render :edit
    end
  end

  def destroy
    @prototype = Prototype.find(params[:id])
    if current_user.id == @prototype.user_id
      @prototype.destroy
    end
    redirect_to root_path
  end

  private

  def prototype_params
  params.require(:prototype).permit(:title, :catch_copy, :concept, :image, :gender_id, :age_id, :occupation_id).merge(user_id: current_user.id)
  end

  def move_to_index
    unless user_signed_in? 
      redirect_to action: :index
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
   def new
   end

   def destroy
    sign_out current_user
    redirect_to new_user_registration_path
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/prototypes_helper.rb
module PrototypesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_with model: [@prototype, @comment], method: :post do |f| %>
          <div class="field">
      <%= f.label :content, "コメント" %><br />
      <%= f.text_field :content, id:"comment_content" %>
        </div>
     <div class="actions">
     <%= f.submit "送信する", class: :form__btn  %>
        </div>
        <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>モブスト</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>
          <%# ログインしているときは以下を表示するようにしましょう %>
          <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
              <%= link_to "モブジェネレーション", new_prototype_path, class: :nav__btn %>
            </div>
            <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <%end%>
          <%# // ログインしていないときは上記を表示するようにしましょう %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">モブスト © All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/prototypes/_form.html.erb
<%= form_with model: @prototype, local: true do |f|%>
  <div class="field">
    <%= f.label :title, "名前" %><br />
    <%= f.text_field :title, id:"prototype_title", value: @prototype.title.presence %>
  </div>

  <div class="field">
    <%= f.label :catch_copy, "口グセ" %><br />
    <%= f.text_area :catch_copy, class: :form__text, id:"prototype_catch_copy", value: @prototype.catch_copy.presence %>
  </div>

  <div class="field">
    <%= f.label :concept, "コンセプト" %><br />
    <%= f.text_area :concept, class: :form__text, id:"prototype_concept", value: @prototype.concept.presence %>
  </div>

  <div class="field">
    <%= f.label :gender_id, "性別" %><br />
    <%= f.collection_select :gender_id, Gender.all, :id, :name %>
  </div>

  <div class="field">
    <%= f.label :age_id, "年齢" %><br />
    <%= f.collection_select :age_id, Age.all, :id, :name %>
  </div>

  <div class="field">
    <%= f.label :occupation_id, "職業" %><br />
    <%= f.collection_select :occupation_id, Occupation.all, :id, :name %>
  </div>

  <div class="field">
    <%= f.label :image, "イメージ" %><br />
    <%= f.file_field :image, id:"prototype_image" %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/prototypes/_prototype.html.erb
<div class="card">
  <%= link_to image_tag(prototype.image, class: :card__img ), prototype_path(prototype)%>
  <div class="card__body">
    <%= link_to prototype.title, prototype_path(prototype), class: :card__title %>
    <p class="card__summary">
      <%= prototype.catch_copy %>
      <%= link_to "by #{prototype.user.nickname}", user_path(prototype.user) %>
    </p>
  </div>
</div>

app/views/prototypes/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">編集</h2>
      <%= render partial: 'form', locals: { prototype: @prototype } %>
    </div>
  </div>
</div>

app/views/prototypes/index.html.erb
<main class="main">
  <div class="inner">

  <%= form_tag(prototypes_path, method: :get, class: "search-form") do %>
  <%= select_tag :gender_id, options_for_select(Gender.all.map { |gender| [gender.name, gender.id] }, params[:gender_id]), prompt: '性別で検索' %>
  <%= select_tag :age_id, options_for_select(Age.all.map { |age| [age.name, age.id] }, params[:age_id]), prompt: '年齢で検索' %>
  <%= submit_tag "検索", class: "btn" %>
  <% end %>

    <% if user_signed_in? && current_user.present? %>
      <div class="greeting">
        <%= link_to "こんにちは、#{current_user.nickname}さん", user_path(current_user)%>
      </div>
    <% end %>

    <div class="card__wrapper">
      <%= render partial: "prototype", collection: @prototypes %>
    </div>
  </div>
</main>

app/views/prototypes/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規投稿</h2>
        <%= render partial: "form", locals: { prototype: @prototype } %>
    </div>
  </div>
</div>

app/views/prototypes/show.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <p class="prototype__hedding">
        <%= @prototype.title %>
      </p>
      <%= link_to "by #{@prototype.user.nickname}", user_path(@prototype.user),class: :prototype__user %>

        <%#条件分岐%>
      <% if user_signed_in? && current_user.id == @prototype.user_id %>
        <div class="prototype__manage">
          <%= link_to "編集する", edit_prototype_path(@prototype), class: :prototype__btn %>
          <%= link_to "削除する", prototype_path(@prototype), method: :delete, class: :prototype__btn %>
        </div>
      <%end%>
      <%# // プロトタイプの投稿者とログインしているユーザーが同じであれば上記を表示する %>

      <div class="prototype__image">
        <%= image_tag url_for(@prototype.image) %>
      </div>
      <div class="prototype__body">
        <div class="prototype__detail">
          <p class="detail__title">キャッチコピー</p>
          <p class="detail__message">
            <%= @prototype.catch_copy %>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">コンセプト</p>
          <p class="detail__message">
            <%= @prototype.concept %>
          </p>
        </div>
      </div>
      <div class="prototype__comments">
        <%# ログインしているユーザーには以下のコメント投稿フォームを表示する %>
        <% if user_signed_in? %>
          <%= render 'comments/form', comment: @comment, prototype: @prototype %>
      <% end %>
        <%# // ログインしているユーザーには上記を表示する %>
        <ul class="comments_lists">
          <%# 投稿に紐づくコメントを一覧する処理を記述する %>
            <% @comments.each do |comment| %>
            <li class="comments_list">
              <%= comment.content %>
              <%= link_to "(#{comment.user.name})", user_path(comment.user), class: :comment_user %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= @user.name %>さんの情報
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">名前</th>
            <td class="table__col2"><%= @user.nickname %></td>
          </tr>
          <tr>
            <th class="table__col1">プロフィール</th>
            <td class="table__col2"><%= @user.profile %></td>
          </tr>
          <tr>
            <th class="table__col1">所属</th>
            <td class="table__col2"><%= @user.occupation %></td>
          </tr>
          <tr>
            <th class="table__col1">役職</th>
            <td class="table__col2"><%= @user.position %></td>
          </tr>
        </tbody>
      </table>
      <h2 class="page-heading">
        <%= @user.name %>さんのランク
      </h2>
      <div class="user__card">
        <%= render partial: 'prototypes/prototype', collection: @user.prototypes %>
      </div>
    </div>
  </div>
</div>